title: My Personal Blog
email: your-email@example.com

description: >-
  A personal blog about music, trading card games, and my CMS project.

baseurl: ""
url: ""

github_username: yourgithubname

theme: minima

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "Blog"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
